version: 2.1

parameters:
  build-image:
    type: boolean
    default: false

jobs:
  php80-arm64:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true 
    resource_class: arm.medium
    steps:
      - checkout

      - run: echo "$GHCR_PASSWORD" | docker login ghcr.io -u shyim --password-stdin

      - run: docker build -t ghcr.io/shyim/shopware-php:8.0-arm64 -t ghcr.io/shyim/shopware-php:8.0.28-arm64 -f php/8.0/Dockerfile .

      - run: docker push ghcr.io/shyim/shopware-php:8.0-arm64

      - run: docker push ghcr.io/shyim/shopware-php:8.0.28-arm64

  php80-amd64:
      machine:
        image: ubuntu-2004:current
        docker_layer_caching: true 
      resource_class: medium
      steps:
        - checkout
  
        - run: echo "$GHCR_PASSWORD" | docker login ghcr.io -u shyim --password-stdin
  
        - run: docker build -t ghcr.io/shyim/shopware-php:8.0-amd64 -t ghcr.io/shyim/shopware-php:8.0.28-amd64 -f php/8.0/Dockerfile .
  
        - run: docker push ghcr.io/shyim/shopware-php:8.0-amd64

        - run: docker push ghcr.io/shyim/shopware-php:8.0.28-amd64
  
  php81-arm64:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true 
    resource_class: arm.medium
    steps:
      - checkout

      - run: echo "$GHCR_PASSWORD" | docker login ghcr.io -u shyim --password-stdin

      - run: docker build -t ghcr.io/shyim/shopware-php:8.1-arm64 -t ghcr.io/shyim/shopware-php:8.1.16-arm64 -f php/8.1/Dockerfile .

      - run: docker push ghcr.io/shyim/shopware-php:8.1-arm64

      - run: docker push ghcr.io/shyim/shopware-php:8.1.16-arm64

  php81-amd64:
      machine:
        image: ubuntu-2004:current
        docker_layer_caching: true 
      resource_class: medium
      steps:
        - checkout
  
        - run: echo "$GHCR_PASSWORD" | docker login ghcr.io -u shyim --password-stdin
  
        - run: docker build -t ghcr.io/shyim/shopware-php:8.1-amd64 -t ghcr.io/shyim/shopware-php:8.1.16-amd64 -f php/8.1/Dockerfile .
  
        - run: docker push ghcr.io/shyim/shopware-php:8.1-amd64

        - run: docker push ghcr.io/shyim/shopware-php:8.1.16-amd64
  

  merge-manifest:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true 
    resource_class: medium
    steps:
      - run: echo "$GHCR_PASSWORD" | docker login ghcr.io -u shyim --password-stdin

      - run: docker manifest create ghcr.io/shyim/shopware-php:8.0 --amend ghcr.io/shyim/shopware-php:8.0.28-amd64 --amend ghcr.io/shyim/shopware-php:8.0.28-arm64

      - run: docker manifest create ghcr.io/shyim/shopware-php:8.0.28 --amend ghcr.io/shyim/shopware-php:8.0.28-amd64 --amend ghcr.io/shyim/shopware-php:8.0.28-arm64

      - run: docker manifest push ghcr.io/shyim/shopware-php:8.0

      - run: docker manifest push ghcr.io/shyim/shopware-php:8.0.28

      - run: docker manifest create ghcr.io/shyim/shopware-php:8.1 --amend ghcr.io/shyim/shopware-php:8.1.16-amd64 --amend ghcr.io/shyim/shopware-php:8.1.16-arm64

      - run: docker manifest create ghcr.io/shyim/shopware-php:8.1.16 --amend ghcr.io/shyim/shopware-php:8.1.16-amd64 --amend ghcr.io/shyim/shopware-php:8.1.16-arm64

      - run: docker manifest push ghcr.io/shyim/shopware-php:8.1

      - run: docker manifest push ghcr.io/shyim/shopware-php:8.1.16

workflows:
  build-base-image:
    when: << pipeline.parameters.build-image >>
    jobs:
      - php80-arm64
      - php80-amd64
      - php81-arm64
      - php81-amd64
      - merge-manifest:
          requires:
            - php80-arm64
            - php80-amd64
            - php81-arm64
            - php81-amd64
