name: Generate Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Generate Builds
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Generate files
        run: |
          php generate_shopware.php
          php generate_php.php

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'New docker updates'
          delete-branch: true
          assignees: shyim
          reviewers: shyim
