name: Generate Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update:
    name: Generate Builds
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Generate files
        run: |
          php generate_shopware.php
          php generate_php.php
          
      - name: my-app-install token
        id: gh-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_SECRET }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.gh-app.outputs.token }}
          commit-message: 'New docker updates'
          delete-branch: true
          assignees: shyim
          reviewers: shyim
